import typing

class ZstdDecompressObj:
    def decompress(self, data: bytes) -> bytes: ...
    def flush(self) -> typing.Optional[bytes]: ...

class ZstdDecompresspr:
    def decompressobj(self) -> ZstdDecompressObj: ...
