name: CI

on: [push, pull_request]

jobs:
  Windows:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7 to run nox
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Set up Python ${{ matrix.python-version }}
      if: matrix.python_version != '3.7'
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # Work around https://github.com/theacodes/nox/issues/250
        Remove-Item C:\ProgramData\Chocolatey\bin\python2.7.exe
        py -3.7 -m pip install nox
    - name: Test
      run: |
        nox -s test-${{ matrix.python-version }}
    - name: Coverage upload
      env:
        CODECOV_TOKEN: 3bb38a90-137e-4efe-9627-ca66de472c13
      run: |
        python.exe -m pip install codecov
        python.exe -m codecov -f coverage.xml
